import { Typography } from "@mui/material";
import { type NextPage } from "next";
import Head from "next/head";
import Chat from "~/components/Chat";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Imp-GPT</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Chat />
      </main>
    </>
  );
};

export default Home;
